version: '3.8'
networks:
  mynetwork:
    driver: bridge

services:
  goapp:
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: dockerfile
    container_name: hastane-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  postgres:
    networks:
      - mynetwork
    image: postgres:latest
    container_name: hastane-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: